# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      babel:
        patterns:
        - "@babel*"
      eslint:
        patterns:
        - "eslint*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
