ignore:
- server.mjs
- app.mjs
- data
- routes
- tests
coverage:
  status:
    project:
      controllers:
        paths:
          - controllers/songController.mjs
      services:
        paths:
          - services/songService.mjs
    patch:
      default:
        informational: true